[package]
name = "mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { workspace = true }
tokio = { workspace = true }
common = { path = "../common" }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
schemars = "1.0.4"
serde.workspace = true
