name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check code compiles
        run: cargo check

      - name: Run cargo fmt
        run: cargo fmt
        if: github.event_name == 'push'

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fmt"
          commit_user_name: "clai-ci[bot]"
          commit_user_email: "clai-ci[bot]@users.noreply.github.com"
          commit_author: "clai-ci[bot] <clai-ci[bot]@users.noreply.github.com>"
          file_pattern: "**/*.rs"
        if: github.event_name == 'push'
